<?php
/** @var \Zwernemann\Withdrawal\Block\Order\WithdrawalButton $block */
$order = $block->getOrder();
?>
<?php if ($order && $block->isEnabled()): ?>
    <?php if ($block->hasWithdrawal((int) $order->getEntityId())): ?>
        <td class="p-2">
            <span class="text-base text-inherit">
                <?= $block->escapeHtml(__('Withdrawal submitted')) ?>
            </span>
        </td>
    <?php elseif ($block->isWithdrawalAllowed($order)): ?>
        <td class="pt-1 pb-2 px-2">
            <a href="<?= $block->escapeUrl($block->getViewUrl((int) $order->getEntityId())) ?>"
               class="btn btn-primary btn-sm text-sm py-1 px-2 min-w-0 justify-center"
               title="<?= $block->escapeHtmlAttr(__('Withdraw Order')) ?>">
                <span><?= $block->escapeHtml(__('Withdraw')) ?></span>
            </a>
        </td>
    <?php else: ?>
        <td class="p-2">
            <span class="pt-1 text-base text-inherit">
                <?= $block->escapeHtml(__('Period expired')) ?>
            </span>
        </td>
    <?php endif; ?>
<?php endif; ?>
